package com.placeholders.mindquest.user_utils;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

/**
 * A user repository that will allow us to perform user data CRUD (create, read, update , delete) operations without having to write code ourselves.
 * Methods will be automatically generated by Spring MVC, no need for manual implementation.
 * @author marius
 */
public interface UserRepository extends JpaRepository<User, Long> {
    User findByEmail(String email);
    @Modifying
    @Query("delete from User u where u.id=:id")
    void deleteById(@Param("id") long id);
}
