package com.placeholders.mindquest.user_utils;

import org.springframework.data.jdbc.repository.query.Query;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * A user repository that will allow us to perform user data CRUD (create, read, update , delete) operations without having to write code ourselves.
 * Methods will be automatically generated by Spring MVC, no need for manual implementation.
 * @author marius
 */
@Repository
public interface UserRepository extends JpaRepository<User, Long> {
    User findByEmail(String email);

    @Query("""
          DELETE FROM users
          WHERE id=:user_id
          """)
    void deleteById(@Param("user_id") int id);

}
